### ISSUE TITLE
Not equal alternative plots don't include both tails in power calculations for t and Z distributions

### ISSUE THREAD

**Issue by dpnichols811** [metinbulus/pwrss#2] opened 2024-10-02 14:51 UTC
Run the following:

power.t.test(ncp = .05 * sqrt(30), df = 29, alpha = .05, plot = TRUE)

power.z.test(ncp = (.51 - .5) / sqrt((.51 * .49) / 20), alpha = 0.05, plot = TRUE)

Compare the printed output power values to the ones from the plots, and also notice that the hatching applied to the right of the positive critical value for the null distributions is not applied to the left of the negative critical values.

You can also see the issue in the Shiny app by going to the default landing page, changing mu from .5 to .05, and clicking Update.

**Comment by adrianolszewski** [comment] 2024-10-10 17:44
@metinbulus Yes, I can confirm this behavior as well in the current version.

**Comment by metinbulus** [comment] 2024-12-09 03:15
Thank you both for reporting the issue. The issue is fixed on GitHub repository.

**Closed by metinbulus** 2024-12-09 03:15 UTC
